preset: psr2
risky: false

finder:
  path:
    - "/src/"
  name: "*.php"

disabled:
  - align_double_arrow
  - braces

enabled:
  - align_phpdoc
  - blank_line_before_return
  - cast_spaces
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - compact_nullable_typehint
  - concat_with_spaces
  - declare_equal_normalize
  - declare_strict_types
  - dir_constant
  - function_typehint_space
  - fully_qualified_strict_types
  - hash_to_slash_comment
  - is_null
  - lowercase_cast
  - method_separation
  - multiline_comment_opening_closing
  - native_function_casing
  - native_function_invocation
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_traits
  - no_empty_comment
  - no_empty_statement
  - no_null_property_initialization
  - no_short_bool_cast
  - no_superfluous_phpdoc_tags
  - no_trailing_comma_in_singleline_array
  - no_unneeded_curly_braces
  - no_unneeded_final_method
  - no_unset_cast
  - no_unset_on_property
  - no_unused_imports
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - non_printable_character
  - normalize_index_brace
  - object_operator_without_whitespace
  - property_separation
  - short_array_syntax
  - short_list_syntax
  - short_scalar_cast
  - simplified_null_return
  - single_blank_line_before_namespace
  - single_quote
  - trailing_comma_in_multiline_array
  - yoda_style
